import image1 from "./public/apartment_3-696x475.jpg";
import image2 from "./public/apartment_4-696x465.jpg";
import image3 from "./public/apartment_5-696x413.jpg";
import image4 from "./public/apartment_6-696x425.jpg";
import image5 from "./public/apartment_7-696x464.jpg";
import image6 from "./public/house_8-696x482.jpg";
import image7 from "./public/house_10-696x464.jpg";
import image8 from "./public/apartment_8-696x464.jpg";
import image9 from "./public/apartment_9-696x522.jpg";
import image10 from "./public/apartment_10-696x493.jpg";
import image11 from "./public/apartment_11-696x491.jpg";
import image12 from "./public/apartment_12-696x450.jpg";

import hero1 from "./public/for_sale-1.png";
import hero2 from "./public/temporary_housing.png";
import hero3 from "./public/rentals.png";

import admin from "./public/theresa_simpson-1.jpg";

const properties = [
  {
    image: image1,
    house: "House 1",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/house-1",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image2,
    house: "Apartment 1",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/apartment-1",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image3,
    house: "House 2",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/house-2",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
  {
    image: image4,
    house: "Apartment 2",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/apartment-2",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image5,
    house: "House 3",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/house-3",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image6,
    house: "Apartment 3",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/apartment-3",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
  {
    image: image7,
    house: "House 4",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/house-4",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image8,
    house: "Apartment 4",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/apartment-4",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image9,
    house: "House 5",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/house-5",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
  {
    image: image10,
    house: "Apartment 5",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/apartment-5",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image11,
    house: "House 6",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/house-6",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image12,
    house: "Apartment 6",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/apartment-6",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
  {
    image: image1,
    house: "House 7",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/house-7",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image2,
    house: "Apartment 7",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/apartment-7",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image3,
    house: "House 8",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/house-8",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
  {
    image: image4,
    house: "Apartment 8",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/apartment-8",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image5,
    house: "House 9",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/house-9",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image6,
    house: "Apartment 9",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/apartment-9",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
  {
    image: image7,
    house: "House 10",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/house-10",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image8,
    house: "Apartment 10",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/apartment-10",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image9,
    house: "House 11",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/house-11",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
  {
    image: image10,
    house: "Apartment 11",
    location: "San Jose, California, United States",
    price: "$5600",
    duration: "Per month",
    transaction: "for-sale",
    rating: "",
    link: "/properties/apartment-11",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image1, image2, image3, image4],
  },
  {
    image: image11,
    house: "House 12",
    location: "Portland, Oregon, United States",
    price: "$250",
    duration: "Per week",
    transaction: "hotel-based",
    rating: "",
    link: "/properties/house-12",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image5, image6, image7, image8],
  },
  {
    image: image12,
    house: "Apartment 12",
    location: "Seattle, Washington, United States",
    price: "$40400",
    duration: "Per year",
    transaction: "rentals",
    rating: "",
    link: "/properties/apartment-12",
    noOfBeds: 4,
    noOfBaths: 2,
    livingArea: "125 m2",
    photos: [image9, image10, image11, image12],
  },
];

const authors = [
  {
    name: "Theresa Simpson",
    avatar: admin,
    bio: "Praesent non leo ipsum. Sed tristique quam tellus, et vehicula tellus vestibulum ut. Ut erat magna, aliquet sed posuere ac, fringilla eget urna. Fusce lectus nisl, sollicitudin ut dictum.",
    phone: "202-555-0158",
    email: "test@test.com",
    website: "https://example.com",
    properties: properties.slice(0, 10),
  },
  {
    name: "Miley Reynold",
    avatar: admin,
    bio: "Praesent non leo ipsum. Sed tristique quam tellus, et vehicula tellus vestibulum ut. Ut erat magna, aliquet sed posuere ac, fringilla eget urna. Fusce lectus nisl, sollicitudin ut dictum.",
    phone: "202-555-0158",
    email: "test@test.com",
    website: "https://example.com",
    properties: properties.slice(10, 17),
  },
  {
    name: "Jacob Milikan",
    avatar: admin,
    bio: "Praesent non leo ipsum. Sed tristique quam tellus, et vehicula tellus vestibulum ut. Ut erat magna, aliquet sed posuere ac, fringilla eget urna. Fusce lectus nisl, sollicitudin ut dictum.",
    phone: "202-555-0158",
    email: "test@test.com",
    website: "https://example.com",
    properties: properties.slice(17, 24),
  },
];

const pages = [

  {
    name: "For sale",
    id: "for-sale",
    properties: properties.filter(
      (property) => property.transaction === "for-sale"
    ),
    heroImage: hero1,
  },
  {
    name: "Hotel based",
    id: "hotel-based",
    properties: properties.filter(
      (property) => property.transaction === "hotel-based"
    ),
    heroImage: hero2,
  },
  {
    name: "Rentals",
    id: "rentals",
    properties: properties.filter(
      (property) => property.transaction === "rentals"
    ),
    heroImage: hero3,
  },

]


export { properties, authors, pages };
